:concurrency: 5

:queues:
  - default
  - mailers

:schedule:
  google_calendar_auto_sync:
    cron: "*/60 * * * *"   
    class: "GoogleCalendarAutoSyncWorker"
    queue: "default"
  event_notification:
    cron: "*/1 * * * *"   
    class: "EventNotificationJob"
  announcement_scheduler:
    cron: "*/1 * * * *"   
    class: "AnnouncementSchedulerJob"